# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=datetime.datetime(2016, 4, 21, 15, 5, 38, 497697, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='homepage',
            field=models.CharField(default=datetime.datetime(2016, 4, 21, 15, 5, 56, 980103, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 4, 21, 15, 6, 10, 552336, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
