# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20160421_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='company',
        ),
    ]
