# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_people_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='est_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='people',
            name='position',
            field=models.CharField(default='input your position', max_length=30),
            preserve_default=False,
        ),
    ]
