# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='name',
            new_name='title',
        ),
    ]
