# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(upload_to='static/company'),
        ),
    ]
