# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('intro', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('allday', models.BooleanField()),
                ('homepage', models.URLField()),
                ('photo', models.ImageField(upload_to='static/hangout')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangout.City')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date visited')),
                ('buddy', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='static/hangout')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangout.Place')),
            ],
        ),
    ]
