# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(default='was good'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(to='hangout.Category'),
        ),
    ]
